language: ruby
rvm:
  - 2.1.8
cache: bundler
branches:
  only:
    - master
env:
  global:
    - RACK_ENV=integration
install:
  - bundle check --path=vendor/bundle || (rm -rf vendor && bundle package --all && bundle install --local --jobs=8 --retry=8 --without debugger --path=vendor/bundle)
script:
  - bundle exec rake spec
cache:
  directories:
    - vendor
