require 'rubygems'
require 'fileutils'
require 'rake'
require 'rake/clean'
require 'rake/testtask'
require 'rbconfig'

include Config

desc "Clean any build files for right-popen"
task :clean do
  if File.exists?('ext/Makefile')
    Dir.chdir('ext') do
      sh 'nmake distclean'
    end
  end
  rm 'lib/win32/right_popen.so' if File.file?('lib/win32/right_popen.so')
end

desc "Build right-popen (but don't install it)"
task :build => [:clean] do
  if RUBY_PLATFORM =~ /mswin/
    Dir.chdir('ext') do
      ruby 'extconf.rb'
      sh 'nmake'
    end
    FileUtils::mkdir_p 'lib/win32'
    mv 'ext/right_popen.so', 'lib/win32'
  end
end

desc "Build a binary gem"
task :build_binary_gem => [:build] do
   Dir["*.gem"].each { |gem| rm gem }
   ruby 'right-popen.gemspec'
end

desc 'Install the right-popen library as a gem'
task :install_gem => [:build_binary_gem] do
   file = Dir["*.gem"].first
   sh "gem install #{file}"
end

desc 'Uninstalls and reinstalls the right-popen library as a gem'
task :reinstall_gem do
   sh "gem uninstall right-popen"
   sh "rake install_gem"
end
